# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: en
reviews:
  profile: chill
  auto_review:
    enabled: true
    drafts: false
  path_filters:
    - "!*.md"
    - "!LICENSE"
    - "!data/**"
chat:
  auto_reply: true
